config/routes.rb
IndependentStudy::Application.routes.draw do
  root :to => 'requests#index'
  resources :requests
  resources :messages
  resources :users

  match "/auth/:provider/callback" => "users#new"
  match "/auth/failure" => "sessions#failure"

  get 'session/destroy'
  get 'session/create'
  get 'session/intermediate'

  get 'requests/search'
  post 'requests/search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>onLoan</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
            <a class="brand" href="/">onLoan</a>
            <%=link_to "Post a Request", new_request_path, class: "btn pull-left"%>
            <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <ul class="nav pull-right nav-collapse">
              <li class="search-query">
               <%= render partial: 'requests/search' %>
              </li>
              <li>
                <%if signed_in?%>
                  <%=link_to "Sign out", controller: "session", action: "destroy"%>
                <%else%>
                  <%=link_to "Sign in", controller: "session", action: "create"%>
                <%end%>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
          

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span10 offset1">
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <div >
          <p>Created by Kim Merrill and <a href="http://twitter.com/jessepollak"
			target="_blank">@jessepollak</a><br></br></p>
        </div>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>